Top2000MVC/Top2000MVC/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Top2000MVC.Models;

namespace Top2000MVC.Controllers
{
    public class ListController : Controller
    {
        private Top2000Context db = new Top2000Context();
        

        // GET: List
        ///
        public ActionResult ListIndex(int year = 2019)
        {
            try
            {
                var cy = DateTime.Parse(year.ToString() + "-01-01");
                var sort = from r in db.Rank
                    where r.year == cy
                    select r;
                ViewBag.year = cy.Year;
                return View(sort.ToList());

            }
            catch (FormatException)
            {
                ViewBag.Error = "Er is geen juist jaartal opgeggeven";
                return View("Error");
            }
            
        }


        
    }
}

Top2000MVC/Top2000MVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Top2000MVC.Models;

namespace Top2000MVC.Controllers
{
    public class UsersController : Controller
    {

        private Top2000Context db = new Top2000Context();
        // GET: Users
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                return View(db.AspNetUsers.ToList());
            }
            else
            {
                ViewBag.Error = "U heeft geen toegang om deze pagina te bekijken.";
                return View("Error");
            }
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {

            ViewBag.UserName = db.AspNetUsers.Find(id).UserName; ;
            return View();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

        }
        // Niet af gemaakt Dus let hier niet op
        //
        // // POST: Users/Edit/5
        // [HttpPost]
        // public ActionResult Edit(int id, FormCollection collection)
        // {
        //     if (ModelState.IsValid)
        //     {
        //         var user = new ApplicationUser {UserName = model.Email, Email = model.Email};
        //         var result = await UserManager, ;
        //         if (result.Succeeded)
        //         {
        //             return RedirectToAction("Index", "Home");
        //         }
        //
        //         AddErrors(result);
        //     }
        // }
        //
        // // GET: Users/Delete/5
        //     public ActionResult Delete(int id)
        // {
        //     return View();
        // }
        //
        // // POST: Users/Delete/5
        // [HttpPost]
        // public ActionResult Delete(int id, FormCollection collection)
        // {
        //     try
        //     {
        //         // TODO: Add delete logic here
        //
        //         return RedirectToAction("Index");
        //     }
        //     catch
        //     {
        //         return View();
        //     }
        // }
    }
}

Top2000MVC/Top2000MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Radio 2 - Top2000</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("De Top2000", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Over", "About", "Home")</li>
                    <li>@Html.ActionLink("Lijst", "ListIndex", "List")</li>
                    @if (User.IsInRole("Admin"))
                    {

                        <li>
                            @Html.ActionLink("Gebruikers", "Index", "Users", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Top2000 - Sprint 12</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>